In [1]:
import os, sys
sys.path.append('../src/')
import numpy as np
import torch
from torch import nn
from torchvision import transforms
from torch.utils.data import Dataset, DataLoader
import torch.nn.functional as F
from torch.autograd import Variable
from data import *
from model import CNN
from download_dataset import download_dataset
from sklearn.model_selection import KFold
%load_ext autoreload
%autoreload 2

In [99]:
D = LoadDataset(batch_size_train=1, batch_size_test=1)
idxs = np.arange(D.__len__())
kf = KFold(n_splits=10)

In [100]:
D.__len__()
idxs = np.arange(D.__len__())
kf = KFold(n_splits=10)

In [101]:
for i, idx in enumerate(kf.split(idxs)):
    train_loader, test_loader = D[idx]
    

0
5443 605
1
5443 605
2
5443 605
3
5443 605
4
5443 605
5
5443 605
6
5443 605
7
5443 605
8
5444 604
9
5444 604


In [82]:
train_idx, test_idx = idx

In [83]:
len(train_idx)

5444

In [60]:
X_train.shape

(5444, 42, 700)

In [62]:
X_test.shape

(604, 42, 700)

In [45]:
loaded = np.load('../data/cb513_.npz')

In [49]:
X, y, mask = loaded['X'], loaded['y'], loaded['mask']

In [47]:
X.shape

(6048, 42, 700)

## device

In [2]:
use_cuda = not False and torch.cuda.is_available()
device = torch.device("cuda" if use_cuda else "cpu")

## model

In [36]:
? np.save()

In [19]:
? np.append()

## data loader

In [2]:
batch_size_train = 128
batch_size_test = 1

train_loader, test_loader = make_dataloader(batch_size_train, batch_size_test)

Train path is downloaded ...
Loading train data ...
Loading splits ...
Loading test data ...
(5534, 42, 700)
(5534, 700)


In [5]:
model.train()
for data, target, mask in train_loader:
    data, target = data.to(device), target.to(device)
    out = model(data)
    break

torch.Size([128, 42, 700])
torch.Size([128, 192, 700])


In [6]:
out.shape

torch.Size([128, 700, 8])

In [7]:
a = F.softmax(out, dim=2)

In [3]:
model = CNN(42, 64, 1).to(device).double()

In [4]:
model = CNN(42, 64, 1).to(device).double()

In [5]:
model = CNN(42, 64, 1).to(device).double()

In [6]:
model = CNN(42, 64, 1).to(device).double()

In [7]:
model = CNN(42, 64, 1).to(device).double()

In [8]:
model = CNN(42, 64, 1).to(device).double()

In [8]:
a.shape

torch.Size([128, 700, 8])

In [12]:
a[0, 0]

tensor([ 0.1263,  0.1284,  0.1196,  0.1252,  0.1190,  0.1306,  0.1202,
         0.1307], dtype=torch.float64, device='cuda:0')

In [96]:
a = out3[:, 0, :]

In [135]:
b =  F.softmax(out3, dim=2)

In [140]:
out3.shape

torch.Size([700, 64, 8])

In [163]:
mask.shap

torch.Size([30, 700])

In [225]:
mask.sum(dim=1).shape

torch.Size([64])

In [226]:
criterion = nn.CrossEntropyLoss(ignore_index=mask.sum(dim=1))

In [177]:
out3.shape

torch.Size([700, 64, 8])

In [174]:
target.shape

torch.Size([64, 700])

In [207]:
target.transpose(0, 1)[0].long()

tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0])

In [187]:
out3[0].shape

torch.Size([64, 8])

In [228]:
mask.shape

torch.Size([64, 700])

In [236]:
def criterion(out, target, mask):
    a = torch.tensor([nn.CrossEntropyLoss()(o, t) 
                      for o, t, m in zip(out, target, mask)])
    return a.sum

In [241]:
data[0][0]

tensor([ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  1.0000,
         0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0122,  0.0014,  0.0059,  0.0088,  0.0006,  0.0029,  0.0028,
         0.0015,  0.0099,  0.0013,  0.0020,  0.0034,  0.9999,  0.0074,
         0.0030,  0.0124,  0.0093,  0.0023,  0.0006,  0.1192,  0.0012], dtype=torch.float64)

In [240]:
data[0].shape

torch.Size([700, 42])

In [239]:
out3[0].shape

torch.Size([64, 8])

In [237]:
criterion(out3, target.transpose(0, 1), mask.sum(dim=1).numpy())

TypeError: nll_loss(): argument 'ignore_index' (position 5) must be int, not numpy.float64

In [232]:
mask.sum(dim=1).numpy()

array([186., 385., 269., 261., 303.,  45., 154.,  84., 359., 134., 197.,
       142., 462., 258., 302.,  69.,  48., 135.,  64., 397., 185., 306.,
       258., 273.,  86., 158., 386., 111., 122., 203., 188., 293., 179.,
       305., 134., 406., 265., 147., 154., 193., 362., 393., 158., 179.,
       386.,  85., 413., 105., 388., 138., 302., 152., 191., 227., 181.,
       252., 197.,  63.,  98., 391., 166., 133., 102., 307.])

In [217]:
Variable(1)

TypeError: Variable data has to be a tensor, but got int

In [221]:
target.transpose(0, 1).shape

torch.Size([700, 64])

In [227]:
torch.sum(torch.tensor([criterion(o, t.long()) for o, t in zip(out3, target.transpose(0, 1))]))

TypeError: nll_loss(): argument 'ignore_index' (position 5) must be int, not Tensor

In [167]:
mask.sum(dim=1)

tensor([ 186.,  385.,  269.,  261.,  303.,   45.,  154.,   84.,  359.,
         134.,  197.,  142.,  462.,  258.,  302.,   69.,   48.,  135.,
          64.,  397.,  185.,  306.,  258.,  273.,   86.,  158.,  386.,
         111.,  122.,  203.,  188.,  293.,  179.,  305.,  134.,  406.,
         265.,  147.,  154.,  193.,  362.,  393.,  158.,  179.,  386.,
          85.,  413.,  105.,  388.,  138.,  302.,  152.,  191.,  227.,
         181.,  252.,  197.,   63.,   98.,  391.,  166.,  133.,  102.,
         307.], dtype=torch.float64)

In [170]:
target.shape

torch.Size([64, 700])

In [146]:
mask.shape

torch.Size([64, 700])

In [136]:
? F.softmax()

In [137]:
b.shape

torch.Size([700, 64, 8])

In [138]:
b[:, 0, :][0].sum()

tensor(1.0000, dtype=torch.float64)

In [93]:
out4 = F.log_softmax(out3, dim=0)

/home/lab/takato/.pyenv/versions/anaconda3-4.3.1/envs/ubuntu/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  """Entry point for launching an IPython kernel.


In [92]:
out4[:, 0, :].sum()

tensor(-36686.0695, dtype=torch.float64)

In [61]:
17 // 2

8

In [27]:
m = nn.Conv1d(16, 33, 3, stride=2)
>>> input = torch.randn(20, 16, 50)
>>> output = m(input)

In [28]:
m

Conv1d(16, 33, kernel_size=(3,), stride=(2,))

In [29]:
input.shape

torch.Size([20, 16, 50])