In [455]:
import os, sys
sys.path.append('../src/')
import numpy as np
import torch
from torch import nn
from torchvision import transforms
from torch.utils.data import Dataset, DataLoader
import torch.nn.functional as F
from torch.autograd import Variable
from data import *
from model import Net
from download_dataset import download_dataset
from sklearn.model_selection import KFold
from download_dataset import get_train
from utils import LossFunc

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [236]:
download_dataset()

Download CB513 dataset ...
Saved CB513 dataset in ../data/cb513.npz


In [457]:
loss = LossFunc()

In [344]:
D = LoadDataset(batch_size_train=5, batch_size_test=1)
idxs = np.arange(D.__len__())
kf = KFold(n_splits=10)

In [345]:
D.__len__()
idxs = np.arange(D.__len__())
kf = KFold(n_splits=10)

In [347]:
for i, idx in enumerate(kf.split(idxs)):
    train_loader, test_loader = D[idx]
    break

In [352]:
loss(out, target, seq_len)

tensor(10.4035)

## device

In [83]:
use_cuda = not False and torch.cuda.is_available()
device = torch.device("cuda" if use_cuda else "cpu")

## model

In [348]:
model = Net().to(device)

In [356]:
out.shape

torch.Size([5, 700, 8])

In [358]:
out.argmax(dim=2).shape

torch.Size([5, 700])

In [360]:
a = torch.rand(5)

In [366]:
target.shape

torch.Size([5, 700])

In [369]:
a = torch.Tensor([2, 2, 5])

In [373]:
b = torch.Tensor([2, 2, 5])

In [374]:
(a == b).sum()

tensor(3)

In [451]:
def accuracy(out, target, seq_len):
    """
    out.shape : (batch_size, seq_len, class_num)
    target.shape : (class_num, seq_len)
    seq_len.shape : (batch_size)
    """
    out = out.cpu().data.numpy()
    target = target.cpu().data.numpy()
    seq_len = seq_len.cpu().data.numpy()
    
    out = out.argmax(axis=2)
    return np.array([np.equal(o[:l], t[:l]).sum()/l
                     for o, t, l in zip(out, target, seq_len)]).mean()

In [452]:
accuracy(out, target, seq_len)

0.09307678732536824

In [415]:
o = out.argmax(dim=2)[0]
t = target[0]
l = seq_len[0]

In [440]:
out_numpy = out.cpu().data.numpy()

In [387]:
accuracy(out, target, seq_len)

RuntimeError: Expected object of type torch.cuda.LongTensor but found type torch.LongTensor for argument #2 'other'

In [375]:
(out.argmax(dim=2) == target).sum()/

tensor(74, device='cuda:0')

In [361]:
a

tensor([ 0.9733,  0.9279,  0.6049,  0.1149,  0.3707])

In [362]:
a.argmax(dim=0)

tensor(0)

## data loader

In [458]:
model.train()
for data, target, seq_len in train_loader:
    data, target, seq_len = \
        data.to(device), target.to(device), seq_len.to(device)
    out = model(data)
    break

In [459]:
loss(out, target, seq_len)

tensor(10.4048)

In [460]:
accuracy(out, target, seq_len)

0.0756616446419078

In [240]:
out.shape

torch.Size([5, 700, 8])

In [94]:
out[:, :, :250].shape

torch.Size([1, 8, 250])

In [96]:
mask.sum()

tensor(314., dtype=torch.float64)

In [6]:
out.shape

torch.Size([128, 700, 8])

In [7]:
a = F.softmax(out, dim=2)

In [3]:
model = CNN(42, 64, 1).to(device).double()

In [4]:
model = CNN(42, 64, 1).to(device).double()

In [5]:
model = CNN(42, 64, 1).to(device).double()

In [6]:
model = CNN(42, 64, 1).to(device).double()

In [7]:
model = CNN(42, 64, 1).to(device).double()

In [8]:
model = CNN(42, 64, 1).to(device).double()

In [8]:
a.shape

torch.Size([128, 700, 8])

In [12]:
a[0, 0]

tensor([ 0.1263,  0.1284,  0.1196,  0.1252,  0.1190,  0.1306,  0.1202,
         0.1307], dtype=torch.float64, device='cuda:0')

In [96]:
a = out3[:, 0, :]

In [135]:
b =  F.softmax(out3, dim=2)

In [140]:
out3.shape

torch.Size([700, 64, 8])

In [163]:
mask.shap

torch.Size([30, 700])

In [225]:
mask.sum(dim=1).shape

torch.Size([64])

In [226]:
criterion = nn.CrossEntropyLoss(ignore_index=mask.sum(dim=1))

In [177]:
out3.shape

torch.Size([700, 64, 8])

In [174]:
target.shape

torch.Size([64, 700])

In [207]:
target.transpose(0, 1)[0].long()

tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0])

In [187]:
out3[0].shape

torch.Size([64, 8])

In [228]:
mask.shape

torch.Size([64, 700])

In [236]:
def criterion(out, target, mask):
    a = torch.tensor([nn.CrossEntropyLoss()(o, t) 
                      for o, t, m in zip(out, target, mask)])
    return a.sum

In [241]:
data[0][0]

tensor([ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  1.0000,
         0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0122,  0.0014,  0.0059,  0.0088,  0.0006,  0.0029,  0.0028,
         0.0015,  0.0099,  0.0013,  0.0020,  0.0034,  0.9999,  0.0074,
         0.0030,  0.0124,  0.0093,  0.0023,  0.0006,  0.1192,  0.0012], dtype=torch.float64)

In [240]:
data[0].shape

torch.Size([700, 42])

In [239]:
out3[0].shape

torch.Size([64, 8])

In [237]:
criterion(out3, target.transpose(0, 1), mask.sum(dim=1).numpy())

TypeError: nll_loss(): argument 'ignore_index' (position 5) must be int, not numpy.float64

In [232]:
mask.sum(dim=1).numpy()

array([186., 385., 269., 261., 303.,  45., 154.,  84., 359., 134., 197.,
       142., 462., 258., 302.,  69.,  48., 135.,  64., 397., 185., 306.,
       258., 273.,  86., 158., 386., 111., 122., 203., 188., 293., 179.,
       305., 134., 406., 265., 147., 154., 193., 362., 393., 158., 179.,
       386.,  85., 413., 105., 388., 138., 302., 152., 191., 227., 181.,
       252., 197.,  63.,  98., 391., 166., 133., 102., 307.])

In [217]:
Variable(1)

TypeError: Variable data has to be a tensor, but got int

In [221]:
target.transpose(0, 1).shape

torch.Size([700, 64])

In [227]:
torch.sum(torch.tensor([criterion(o, t.long()) for o, t in zip(out3, target.transpose(0, 1))]))

TypeError: nll_loss(): argument 'ignore_index' (position 5) must be int, not Tensor

In [167]:
mask.sum(dim=1)

tensor([ 186.,  385.,  269.,  261.,  303.,   45.,  154.,   84.,  359.,
         134.,  197.,  142.,  462.,  258.,  302.,   69.,   48.,  135.,
          64.,  397.,  185.,  306.,  258.,  273.,   86.,  158.,  386.,
         111.,  122.,  203.,  188.,  293.,  179.,  305.,  134.,  406.,
         265.,  147.,  154.,  193.,  362.,  393.,  158.,  179.,  386.,
          85.,  413.,  105.,  388.,  138.,  302.,  152.,  191.,  227.,
         181.,  252.,  197.,   63.,   98.,  391.,  166.,  133.,  102.,
         307.], dtype=torch.float64)

In [170]:
target.shape

torch.Size([64, 700])

In [146]:
mask.shape

torch.Size([64, 700])

In [136]:
? F.softmax()

In [137]:
b.shape

torch.Size([700, 64, 8])

In [138]:
b[:, 0, :][0].sum()

tensor(1.0000, dtype=torch.float64)

In [93]:
out4 = F.log_softmax(out3, dim=0)

/home/lab/takato/.pyenv/versions/anaconda3-4.3.1/envs/ubuntu/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  """Entry point for launching an IPython kernel.


In [92]:
out4[:, 0, :].sum()

tensor(-36686.0695, dtype=torch.float64)

In [61]:
17 // 2

8

In [27]:
m = nn.Conv1d(16, 33, 3, stride=2)
>>> input = torch.randn(20, 16, 50)
>>> output = m(input)

In [28]:
m

Conv1d(16, 33, kernel_size=(3,), stride=(2,))

In [29]:
input.shape

torch.Size([20, 16, 50])